# Generated by Django 5.1.1 on 2024-09-27 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_todo_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="date_created",
        ),
    ]
