# Generated by Django 5.1.1 on 2024-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_todo_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
